# keploy-config.yaml
record:
  path: ""
  command: ""
  containerName: ""
  networkName: ""
  delay: 5
  passThroughPorts: []
  passThroughURL: []
  passThroughHeader: []

test:
  path: ""
  command: ""
  containerName: ""
  networkName: ""
  testSets: []
  delay: 5
  apiTimeout: 5
  passThroughPorts: []