# keploy-config.yaml
record:
  path: ""
  command: ""
  containerName: ""
  networkName: ""
  delay: 5
  passThroughPorts: []
  filters: {
    url : [],
    header: []
  }

test:
  path: ""
  command: ""
  containerName: ""
  networkName: ""
  testSets: []
  delay: 5
  apiTimeout: 5
  passThroughPorts: []