version: api.keploy.io/v1beta2
kind: SQL
name: config
spec:
    metadata:
        operation: HANDSHAKE_RESPONSE
        responseOperation: HANDSHAKE_RESPONSE_OK
    requests:
        - header:
            packet_length: 104
            packet_number: 0
            packet_type: HANDSHAKE_RESPONSE
          message:
            capability_flags: 696973
            max_packet_size: 0
            character_set: 45
            reserved:
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
            username: user
            auth_data:
                - 248
                - 3
                - 99
                - 187
                - 66
                - 41
                - 250
                - 164
                - 65
                - 191
                - 73
                - 22
                - 130
                - 37
                - 207
                - 16
                - 54
                - 197
                - 168
                - 139
                - 30
                - 209
                - 0
                - 16
                - 106
                - 29
                - 199
                - 235
                - 65
                - 96
                - 212
                - 243
            database: shorturl_db
            auth_plugin_name: caching_sha2_password
    responses:
        - header:
            packet_length: 74
            packet_number: 0
            packet_type: MySQLHandshakeV10
          message:
            protocol_version: 10
            server_version: 8.0.33
            connection_id: 16
            auth_plugin_data:
                - 2
                - 102
                - 17
                - 112
                - 26
                - 57
                - 29
                - 34
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 0
                - 83
                - 68
                - 61
            capability_flags: 50331647
            character_set: 0
            status_flags: 57343
            auth_plugin_name: caching_sha2_password
        - header:
            packet_length: 2
            packet_number: 0
            packet_type: HANDSHAKE_RESPONSE_OK
          message:
            packet_indicator: AuthMoreData
            plugin_details:
                type: cachingSha2PasswordFastAuthSuccess
                message: Ok
            remaining_bytes:
                - 7
                - 0
                - 0
                - 3
                - 0
                - 0
                - 0
                - 2
                - 0
                - 0
                - 0
    created: 1692524138
