version: api.keploy.io/v1beta2
kind: Mongo
name: config
spec:
    metadata:
        operation: '{ OpQuery flags: [SecondaryOK], fullCollectionName: admin.$cmd, numberToSkip: 0, numberToReturn: -1, query: {"isMaster": {"$numberInt":"1"},"helloOk": true,"compression": [],"client": {"driver": {"name": "mongo-go-driver","version": "v1.8.3"},"os": {"type": "linux","architecture": "amd64"},"platform": "go1.20.5"}}, returnFieldsSelector:  }'
    requests:
        - header:
            length: 230
            requestId: 2
            responseTo: 0
            Opcode: 2004
          message:
            flags: 4
            collection_name: admin.$cmd
            number_to_skip: 0
            number_to_return: -1
            query: '{"isMaster":{"$numberInt":"1"},"helloOk":true,"compression":[],"client":{"driver":{"name":"mongo-go-driver","version":"v1.8.3"},"os":{"type":"linux","architecture":"amd64"},"platform":"go1.20.5"}}'
            return_fields_selector: ""
          read_delay: 1089359
    responses:
        - header:
            length: 329
            requestId: 238
            responseTo: 2
            Opcode: 1
          message:
            response_flags: 8
            cursor_id: 0
            starting_from: 0
            number_returned: 1
            documents:
                - '{"helloOk":true,"ismaster":true,"topologyVersion":{"processId":{"$oid":"64b8e103454120d634bf206e"},"counter":{"$numberLong":"0"}},"maxBsonObjectSize":{"$numberInt":"16777216"},"maxMessageSizeBytes":{"$numberInt":"48000000"},"maxWriteBatchSize":{"$numberInt":"100000"},"localTime":{"$date":{"$numberLong":"1689858425528"}},"logicalSessionTimeoutMinutes":{"$numberInt":"30"},"connectionId":{"$numberInt":"12"},"minWireVersion":{"$numberInt":"0"},"maxWireVersion":{"$numberInt":"17"},"readOnly":false,"ok":{"$numberDouble":"1.0"}}'
          read_delay: 58621
    created: 1689858425
